name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - staging

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.JUMPHOST }}
          proxy_port: ${{ secrets.JUMPPORT }}
          proxy_username: ${{ secrets.JUMPUSER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.JUMPPORT }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging
        run: |
          scp -P 22999 test.txt ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}