name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          ssh <staging_server> 'cd /path/to/stagingwp && git fetch && git checkout staging && git pull origin staging'

  deploy_to_production:
    needs: [deploy_to_staging]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          ssh <production_server> 'cd /path/to/productionwp && git fetch && git checkout production && git pull origin production'
