name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.JUMPHOST }}
          proxy_port: ${{ secrets.JUMPPORT }}
          proxy_username: ${{ secrets.JUMPUSER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.JUMPPORT }}
          script: |
            # Update staging branch
            git checkout staging
            git pull origin development

            git push origin staging

            # Update public_html/cicdtst folder
            ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd public_html/cicdtst && git pull origin staging"