name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands to install dependencies for your project

      - name: Run tests
        run: |
          # Add commands to run tests for your project

  staging-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands to install dependencies for your project

      - name: Deploy to staging
        run: |
          # Add commands to deploy your project to the staging environment

  production-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands to install dependencies for your project

      - name: Deploy to production
        run: |
          # Add commands to deploy your project to the production environment
