name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract branch name
      id: branch_name
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Use branch name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Connect to server and update code via SSH
      uses: appleboy/ssh-action@master
      with:
        proxy_host: ${{ secrets.JUMPHOST }}
        proxy_port: ${{ secrets.JUMPPORT }}
        proxy_username: ${{ secrets.JUMPUSER }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.JUMPPORT }}
        script: |
          cd public_html/cicdtst
          git checkout ${{ env.BRANCH_NAME }}
          git pull
