name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - staging

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging
        run: |
          # Replace `stagingwp` with the SSH information for your staging server
          ssh stagingwp@cc1.severalnines.com 'cd /path/to/stagingwp && git fetch origin && git checkout staging'
