name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "charles9s"
          git config user.email "charles@severalnines.com"

      - name: Create pull request from staging branch
        run: |
          git checkout -b pull_request_branch
          git push origin pull_request_branch

      - name: Deploy code to staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd s9s
            # Add any other commands related to your deployment here
            # For example:
            # - npm install
            # - npm run build
            # - ...

      - name: Merge pull request to development
        run: |
          gh pr create --base development --head pull_request_branch --title "Pull Request from staging to development" --body "Automated pull request from CI/CD pipeline"

